---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-centos:7}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
verifier:
  name: goss
  lint:
    name: yamllint
